name: ds-playground
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.1.3
  - jupyterlab=2.2.9
  - seaborn=0.11.0
  - statsmodels=0.12.1
  - scikit-learn=0.23.2
  - flake8=3.8.4
  - black=20.8b1
  - python=3.8.5